### ISSUE TITLE
Install rbenv broken since last release

### ISSUE THREAD

**Issue by egr-ext** [zzet/ansible-rbenv-role#101]
Hi,
The last release has broken the rbenv install for a user.
The issue seems to come from this block of code, it skips the rbenv install:
```
- name: install ruby {{ item[2].version }} for select users
  shell: $SHELL -lc "{{ rbenv_root }}/bin/rbenv install {{ item[2].version }}"
  become: yes
  become_user: "{{ item[1] }}"
  with_nested:
    - "{{ rbenv_versions.results }}"
    - "{{ rbenv_users }}"
    - "{{ rbenv.rubies }}"
  when:
    - item[0].rc == 0
    - item[0].item[0] == item[1]
    - item[2].version not in item[0].stdout_lines
  ignore_errors: yes
  environment: "{{ item[2].env | default({}) | combine({ 'TMPDIR': rbenv_tmpdir }) }}"
```
