### ISSUE TITLE
Fails on Debian Stretch due to permissions

### ISSUE THREAD

**Issue by mkllnk** [zzet/ansible-rbenv-role#116]
I ran version 2.2.6 and 3.3.6 on Debian Jessy without a problem. But on Debian Stretch I get the following error:

```
TASK [zzet.rbenv : checkout rbenv_repo for selected users] *********************************************************************************
fatal: [vagrant]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/tmp/ansible-tmp-1515564561.64-22943182032838/': Operation not permitted\nchown: changing ownership of '/tmp/ansible-tmp-1515564561.64-22943182032838/git.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

I'm connecting as user `vagrant` to a local virtual machine. The user has full sudo permissions and is supposed to install rbenv for another user. Here is the config from the playbook:

```
    - role: zzet.rbenv
      rbenv:
        env: user
        version: v0.4.0
        default_ruby: 1.9.3-p551
        rubies:
          - version: 1.9.3-p551
      rbenv_owner: "{{ app_user }}"
      rbenv_group: "{{ app_user }}"
      rbenv_users:
        - "{{ app_user }}"
```

I'm using Ansible 2.4.2.0l

**Comment by mkllnk** [comment]
Okay, I'm not 100% sure what the difference between the Jessie and the Stretch image is, but it could be the availability of POSIX.1e filesystem acl support. I found three ways around this:

- Connect as root.
- Put `allow_world_readable_tmpfiles = True` in your `.ansible.cfg` file.
- Install POSIX.1e filesystem acl support (untested).

All this is pretty much mentioned in http://docs.ansible.com/ansible/latest/become.html#becoming-an-unprivileged-user. Maybe since this module uses switching to unprivileged users, this could be mentioned in the README file?

Feel free to close this issue, since it's more an issue of Ansible.

**Comment by Aversiste** [comment]
> Install POSIX.1e filesystem acl support (untested).

This option works well for my use case on Debian stretch. I modified my playbook to look like this:

```
roles:
- role: ansible-rbenv-role
  rbenv_users:
  - redmine
  rbenv_extra_depends:
  - acl
```

It is probably more sensible than messing with `allow_world_readable_tmpfiles`.
