### ISSUE TITLE
ruby cleanup fails

### ISSUE THREAD

**Issue by teadur** [zzet/ansible-rbenv-role#123]
It seems ruby_installed doesnot get populated:

my playbook:

- hosts: rbenv
   gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
   vars:
     rbenv_clean_up: True
     rbenv:
       env: user
       version: v1.1.0
       default_ruby: 2.3.7
       rubies:
       - version: 2.3.7
       - version: 2.4.4
         env:
           RUBY_CONFIGURE_OPTS: "--enable-shared"
 
   roles:
     - role: rbenv
       rbenv_users:
         - user1
         - user2
         - user3
         - user4

TASK [rbenv : check which old rubies to remove for select users] *********************************************************************************************************************************
fatal: [staging.infra.tld.ee]: FAILED! => {"msg": "'ruby_installed' is undefined"}
...ignoring

TASK [rbenv : remove old rubies] *****************************************************************************************************************************************************************
fatal: [staging.infra.tld.ee]: FAILED! => {"msg": "'dict object' has no attribute 'results'"}
...ignoring

**Comment by Matt-Yorkley** [comment]
Yeah, this task fails every time if `rbenv_clean_up` is set to `true`.

**Comment by attenzione** [comment]
@teadur @Matt-Yorkley I have own role `rbenv-extra` with the following tasks:

```yaml
- name: Get ruby versions installed for system
  ansible.builtin.shell: $0 -lc "rbenv versions --bare"
  register: rbenv_versions
  changed_when: false
  ignore_errors: true
  failed_when: false
  check_mode: false

- name: Get old rubies to remove for system
  become: true
  ansible.builtin.set_fact:
    drop_rubies: "{{ rbenv_versions.stdout_lines | list | difference(rbenv.rubies | map(attribute='version') | list) }}"
  when:
    - rbenv_custom_clean_up | bool

- name: Remove old rubies
  become: true
  ansible.builtin.shell: $0 -lc "rm -rf {{ rbenv_root }}/versions/{{ item }}"
  with_items: "{{ drop_rubies }}"
  when:
    - rbenv_custom_clean_up | bool
    - drop_rubies | length > 0
  changed_when: drop_rubies | length > 0

```

`rbenv_custom_clean_up: true # default in role`

@zzet fill free to implement in your role
