### ISSUE TITLE
No idempotency on "install ruby versions for system"

### ISSUE THREAD

**Issue by ahes** [zzet/ansible-rbenv-role#126]
A role does not have `idempotency` which is essential feature of Ansible.
Following task always shows `changed`:

```
TASK [zzet.rbenv : install ruby versions for system] *********************************************************************************************************
changed: [dev-02] => (item={u'version': u'2.5.1'})
```

Role variables:

```
    rbenv:
      env: system
      version: v1.1.1
      default_ruby: 2.5.1
      rubies:
        - version: 2.5.1
```

**Comment by ramonrails** [comment]
```
TASK [zzet.rbenv : check ruby versions installed for system] ********************************************************************************************************
ok: [staging] => (item={'version': '2.7.1', 'env': {'RUBY_CONFIGURE_OPTS': '--enable-shared'}})

TASK [zzet.rbenv : install ruby versions for system] ****************************************************************************************************************
changed: [staging] => (item={'version': '2.7.1', 'env': {'RUBY_CONFIGURE_OPTS': '--enable-shared'}})

```

**Comment by attenzione** [comment]
The system-install task runs `rbenv install --skip-existing` through `shell` with neither `changed_when` nor `creates`, so Ansible reports `changed` on every run even though `--skip-existing` makes rbenv exit immediately. 

The user-install path in the same role already handles this correctly with `creates:` (`tasks/user_install.yml`, "install specified ruby versions for select users"). The system path only needs the same guard:

```yaml
- name: install ruby versions for system
  shell: $0 -lc "rbenv install --skip-existing {{ item.version }}"
  args:
    creates: "{{ rbenv_root }}/versions/{{ item.version }}"
  become: true
  with_items:
    - '{{ rbenv.rubies }}'
  loop_control:
    label: Install {{ item.version }} for system
  environment: "{{ item.env | default({}) | combine({ 'TMPDIR': rbenv_tmpdir }) }}"
```

`rbenv install` creates `{{ rbenv_root }}/versions/<version>`, which is `/usr/local/rbenv/versions/<version>` for `rbenv.env: system`, so once a ruby is built the task is skipped and reports `ok`. First run still installs as before.
