### ISSUE TITLE
error Install with env user at task: initialization to profile system-wide

### ISSUE THREAD

**Issue by ricsdeol** [zzet/ansible-rbenv-role#137]
Hi, first good job with playbook.
So I'm try use this playbook withe   `env: true` but this errors happened:

```yml
TASK [zzet.rbenv : add rbenv initialization to profile system-wide] **********************************************************************************
fatal: [rails_server]: FAILED! => {"changed": false, "checksum": "80e9fe35728856b6e7444cb0fbcc844a8424674c", "gid": 1000, "group": "deployer", "mode": "0664", "msg": "chown failed: [Errno 1] Operation not permitted: '/etc/profile.d/rbenv.sh'", "owner": "deployer", "path": "/etc/profile.d/rbenv.sh", "size": 132, "state": "file", "uid": 1000}
```

I was in doubt why tasks below it's necessary at user environment:
```yml
- name: add rbenv initialization to profile system-wide
  template:
    src: rbenv_user.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  when:
    - (ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin') and rbenv_user_profile
```

I removed this lines at `~/.ansible/roles/zzet.rbenv/tasks/user_install.yml` and works.

Thank You
Bye
