### ISSUE TITLE
[feature request] ability to not install a system ruby version?

### ISSUE THREAD

**Issue by thom-nic** [zzet/ansible-rbenv-role#34]
I want to install rbenv with this role but then not install a ruby version until later in my build when my app sources are checked out.  There's a `.ruby-version` file which defines the proper ruby version (at which point I can just add a `shell: bash -lc rbenv install` line to install the correct ruby version without specifying it anywhere in my ansible vars.  Does that make sense?  Could it be possible to define `rbenv.ruby_version` as an empty/ false value to skip the default install?

**Comment by zzet** [comment]
@thom-nic can you show content of your `.ruby-version` file?

**Comment by thom-nic** [comment]
It's just a single line:
```
2.1.3
```

Rbenv already understands how to process it, it's sort of a generic `.rbenv-version` file.  I just go to the root directory of your project and do `rbenv install`.  rbenv also knows which ruby version to activate when running project executables (`ruby`, `rake`) by looking at the same file.

**Comment by zzet** [comment]
@thom-nic do you need to override ruby version from default 2.2.0 to your 2.1.3?

**Comment by zzet** [comment]
As can you see in Readme - you can setup any ruby with this role.
```
- hosts: all
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.0.0-p353
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - user
```

as example
