### ISSUE TITLE
it is posible to install multiple ruby versions??

### ISSUE THREAD

**Issue by blackjid** [zzet/ansible-rbenv-role#35]
something like this

``` yml
rbenv:
  rbenv_versions: 
  - 2.0.0-p538
  - 2.1.0
```

**Comment by zzet** [comment]
Hi @blackjid! At this moment no. Until April, I will not have time to add this functionality.

**Comment by blackjid** [comment]
I'd be happy to make a PR... 
could you please point me in the right direction???
what should be the definitions??

```yml
- role: zzet.rbenv
      rbenv_users:
        - deploy
      ruby_versions: 
        - 2.0.0-p643
        - 2.1.2
      ruby_global_version: 2.0.0-p643
```

something like that?

**Comment by zzet** [comment]
If we talk about users and the version of Ruby - then we have a matrix:
```yaml
      rbenv_users:
        - deploy
        - other
      ruby_versions: 
        - 2.0.0-p643
        - 2.1.2
```

for deploy and other user will installed all ruby versions from list. I think this is not correct.
It is better for each user to specify which version to put:

like as
```yaml
- rbenv_install:
  - user: deploy
    versions:
      - 2.0.0-p643
      - 2.1.2
```
or as hash
```ruby
{ rbenv_install: [
    { user: deploy, versions: [2.0.0-p643, 2.1.2] },
    { user: other, versions: [2.1.2] }
]}
```

I need to take a break and think about how best to do this. We should bear in mind that this is a rare case and role overload is not necessary. Most users will want to install 1 ruby version for 1 or more users. If we say that we need to put more than one version, you should talk about what you need or different users on different versions of one or several versions, but at the same time indicate which of them is used by default (for example last defined in versions list).

In addition, changes in key version may be a surprise to those who already use role. After these changes will be released major version.

**Comment by zzet** [comment]
@blackjid If you have any thoughts on this issue - I will be glad to consider them

**Comment by zzet** [comment]
Hi @blackjid!

I think this definitions is good (based on default settings):

```yaml
rbenv:
  env: system
  version: v0.4.0
  ruby_version: 2.2.0 # For system install only

# ....

rbenv_install:
  - user: deploy
    ruby_versions:
      - 2.0.0-p643
      - 2.1.2
    default: 2.0.0-p643

  - user: other
    ruby_versions:
      - 2.2.0
      - 2.1.2
    default: 2.2.0

# or 
# rbenv_install: 
#   - { user: deploy, ruby_versions: [2.0.0-p643, 2.1.2], default: 2.0.0-p643 }
#   - { user: other,    ruby_versions: [2.2.0, 2.1.2],          default: 2.2.0 }
```

What do you think about it?
