### ISSUE TITLE
conditional fail with ansible_pkg_mgr

### ISSUE THREAD

**Issue by battlemidget** [zzet/ansible-rbenv-role#37]
Running with ansible 1.7.2 and 1.8.4 (fails on both) on ubuntu 14.04, vagrant 1.6.3, virtualbox 4.3.10

```
TASK: [zzet.rbenv | include env vars] ***************************************** 
ok: [default]

TASK: [zzet.rbenv | update apt cache] ***************************************** 
fatal: [default] => error while evaluating conditional: ansible_pkg_mgr == 'apt'

FATAL: all hosts have already failed -- aborting                                                                                       

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/adam/playbook.retry

default                    : ok=1    changed=0    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

My config:

```
---
- hosts: all
  user: vagrant
  gather_facts: False
  sudo: True
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - vagrant
```

Am I missing something?
