### ISSUE TITLE
Permission denied while install rbenv system wise

### ISSUE THREAD

**Issue by leomao10** [zzet/ansible-rbenv-role#38]
Hi Andrew,
Thanks for the rbenv role, it save me time to setup rbenv in the VMs, however, I ran into a issue when I use the rbenv role. In my playbook, I want to setup a system wise rbenv and have other roles that don't need to run under 'root' user.

At first, I thought I can use 'sudo:yes' like this:

``` yaml
- hosts: default
  roles:
    - role: zzet.rbenv
      sudo: yes
      rbenv:
        env: system
        version: v0.4.0
        ruby_version: 2.1.1
```

But I got permission denied and stopped at the 'clone rbenv repo' task when I run the playbook. It looks like the role do not care about 'sudo:yes' I passed in.

Leo Liang

**Comment by zzet** [comment]
Hi @leomao10,
I'll review your issue after April 20.

**Comment by nakaken0629** [comment]
I can do it by bellow script.

```
- hosts: devservers
  roles:
    - role: zzet.rbenv
      become: true
```

Here is my ansible version.

```
$ ansible --version
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
