### ISSUE TITLE
ruby -v: always display system ruby

### ISSUE THREAD

**Issue by RuslanHamidullin** [zzet/ansible-rbenv-role#40]
Hey Guys,

I use:
```
---
  - name: Configure Server
    hosts: <MY SERVER IP>
    user: ubuntu
    sudo: True

   vars:
      rbenv:
        env: user
        version: v0.4.0
        ruby_version: 2.1.5
   roles:
      - role: zzet.rbenv
        rbenv_users:
          - qae
```

All works fine, but when I ssh to server after provisioning:
```
$ rbenv versions
  system
* 2.1.5 (set by /home/qae/.rbenv/version)

$ rbenv version
2.1.5 (set by /home/qae/.rbenv/version)

$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```
So, looks like it still uses system ruby
Not sure if' it's bug, just decided to ask.
Maybe someone had same issue?

Some info:

1) I use latest version,
Before provision I did:
```
$ ansible-galaxy remove zzet.rbenv
$ ansible-galaxy install zzet.rbenv
```
2) in my /home/qae/.bashrc

```
export PATH=$GEM_HOME/bin:$PATH
export GEM_HOME=/home/qae/.gem

if [ -d "$HOME/.rbenv" ]; then
  export PATH=$HOME/.rbenv/bin:$PATH;
  export RBENV_ROOT=$HOME/.rbenv;
  eval "$(rbenv init -)";
fi

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi
```

3) which ruby
```
$ which ruby
/usr/bin/ruby
```

Thanks :beers:
