### ISSUE TITLE
non bash shell support

### ISSUE THREAD

**Issue by Silox** [zzet/ansible-rbenv-role#46]
Placing the `rbenv init -` script in the `/etc/profile.d` folder (in https://github.com/zzet/ansible-rbenv-role/blob/master/tasks/main.yml#L87) should enable a systemwide installation for all users. This only works with shells using the `/etc/profile.d` folder. For example, [zsh does not rely on this folder](http://askubuntu.com/a/476435/86297), so users using `zsh` end up with unfound commands for both ruby and rbenv.

**Comment by arusa** [comment]
I solved it with a line in my playbook tasks:

```yaml
- name: enable rbenv for zsh
   lineinfile:
     path: /home/xxxx/.zprofile
     line: 'source /etc/profile.d/rbenv.sh'
```

You could create a variable to enable zsh support and then loop through all rbenv-users to add a line to .zprofile in their homedir.

It could also work with a global /etc/zsh/zprofile, but I'm not sure where the optimal place would be and I have read about different places like /etc/zprofile.
