### ISSUE TITLE
rbenv cannot build ruby 2.2.3 with default settings

### ISSUE THREAD

**Issue by dankohn** [zzet/ansible-rbenv-role#49]
The branch of ruby-build specified does not include 2.2.3. The following `playbook.yml` worked for me. It sets ruby-build to use the master branch.
```yml
---
- hosts: all
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.2.3
    rbenv_plugins:
      - { name: "ruby-build",
          repo: "https://github.com/sstephenson/ruby-build.git",
          version: "master" }
```
