### ISSUE TITLE
'rbenv_owner' is undefined

### ISSUE THREAD

**Issue by mkllnk** [zzet/ansible-rbenv-role#71]
I tried to run the example from the readme file:

```yml
- hosts: web
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.0.0-p353
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - user
```

But I get an error:

```
TASK [zzet.rbenv : set rbenv_owner] ********************************************
fatal: [vagrant]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'rbenv_owner' is undefined\n\nThe error appears to have been in '/home/maikel/github/fairfood-install/roles/zzet.rbenv/tasks/main.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set rbenv_owner\n  ^ here\n"}
```

It helps to provide the variables `rbenv_owner` and `rbenv_group`. The readme mentions these variables, but I didn't expect to need them for a user installation (not system). Maybe that should be included in the readme and the example? Ideally, they would default to the target user if `rbenv.env: user`.
