### ISSUE TITLE
Request: Do not use nested variables

### ISSUE THREAD

**Issue by koenpunt** [zzet/ansible-rbenv-role#87]
Now everyone that wants to customise a single option, they have to define the full hash.

With the defaults like:
```
  rbenv:
    env: system
    version: v1.0.0
    default_ruby: 2.3.3
```

Just setting the `default_ruby` requires me to define the full hash, e.g.:

```
- role: rbenv
  rbenv:
    env: system
    version: v1.0.0
    default_ruby: 2.1.6
```

And now since 3.0.0 the `rubies` properties is added, which requires me to add that to my playbool configuration (or add a version constraint).

There a way to get this working by setting [hash-behaviour](http://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour), but this isn't recommended:
> We generally recommend not using this setting unless you think you have an absolute need for it, and playbooks in the official examples repos do not use this setting:

So I suggest to change it to plain variables:

```
  rbenv_env: system
  rbenv_version: v1.0.0
  rbenv_default_ruby: 2.3.3
  rbenv_rubies:
    - version: 2.3.3
```
