### ISSUE TITLE
Please provide more examples?

### ISSUE THREAD

**Issue by sbwoodside** [zzet/ansible-rbenv-role#89]
Can you provide some more examples? For example, how do I simply install a specific version of ruby system-wide? I tried this and got an error:

````
- hosts: whatever
  vars:
    rbenv:
      default_ruby: 2.3.1
      rubies:
      - version: 2.3.1
      
  roles:
    - role: zzet.rbenv
````

Result:

TASK [zzet.rbenv : include env vars] *******************************************
fatal: [monitor.medstack.net]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'env'\n\nThe error appears to have been in '/Users/simon/sandbox/medstack/deployment/ansible/galaxy/zzet.rbenv/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: include env vars\n  ^ here\n"}

Examples for other common configurations would also be welcome.

**Comment by sdejean** [comment]
I think the answer you need is in the example from the README:

```
- hosts: web
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  vars:
    rbenv:
      env: user
      version: v0.4.0
      default_ruby: 2.0.0-p353
      rubies:
      - version: 2.0.0-p353
```

Your error is `The error was: 'dict object' has no attribute 'env'`, meaning that you need to add the `env` property to your dictionary.  You should also specify the `version` property in that dictionary to tell the role which version of `rbenv` to install. Ansible does not merge dictionary values by default, so once you specify one property of that dictionary, you need to specify all of them.
